spring.application.name=EntitiesSpringBoot
### Configuração do H2 em memória para desenvolvimento.
# URL de conexão (mem: testdb indica que é na memória RAM)
spring.datasource.url=jdbc:h2:mem:testdb
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=
server.port=8080

# Dialeto do Hibernate para o H2
spring.jpa.database-platform=org.hibernate.dialect.H2Dialect

# Recria as tabelas toda vez que a aplicação sobe
spring.jpa.hibernate.ddl-auto=create

# Mostra os comandos SQL no console para você debugar
spring.jpa.show-sql=true

# Habilita o painel visual do H2 no navegador
spring.h2.console.enabled=true
spring.h2.console.path=/h2
